#!/bin/bash
set -eu

# IMPECC-JOB

THIS=$( dirname $0 )
LABEL="impecc-job"

source $THIS/utils.sh
PATH=$THIS:$PATH

if (( ${#} != 4 ))
then
  fail "provide SUBMITTER SCRIPT SETTINGS_JOB SETTINGS_IMPECCABLE"
fi
SUBMITTER=$1
SCRIPT_SH=$2
SETTINGS_JOB=$3
SETTINGS_IMPECCABLE=$4

assert-program $SUBMITTER
assert-exist $SCRIPT_SH $SETTINGS_JOB $SETTINGS_IMPECCABLE

# Source this for settings, particularly IMPECCABLE_WORK,
# then pass this into all processed job scripts:
source-checked $SETTINGS_IMPECCABLE
export SETTINGS_IMPECCABLE

msg "WORK:" $IMPECCABLE_WORK

# Provide defaults:
: ${NODES:=1} ${WALLTIME:=00:05:00} ${QUEUE:=debug}

# Source settings to override defaults:
source-checked -v $SETTINGS_JOB

# There is no default NAME:
if [[ ${NAME:-UNSET} == "UNSET" ]]
then
  fail "settings did not set NAME!"
fi

SCRIPT=${SCRIPT_SH%.sh}

export WORKFLOW_STEP=$( realpath $( dirname $SCRIPT ) )

mkdir -pv $IMPECCABLE_WORK/jobs
SUBMIT_SH=$( mktemp --suffix .sh $IMPECCABLE_WORK/jobs/${SCRIPT}_job-XXX )
# Construct output file name:
export OUTPUT=${SUBMIT_SH/.sh/.txt}

msg "writing: " $SUBMIT_SH
# Check for permission errors:
touch $SUBMIT_SH

{
  echo "#!/bin/bash"
  echo "# JOB: NAME:" $NAME
  echo "# JOB: FILE:" $( basename $SCRIPT_SH )
  echo "# JOB: DATE:" $( date-rfc3339 )
  echo
} > $SUBMIT_SH

if [[ $SUBMITTER != "bash" ]]
then
  msg "submitting job..."
  printf "NODES: %4i\n" ${NODES:-1}
  printf "PPN:   %4i\n" ${PPN:-1}
fi

m4 -P $THIS/common.m4 $SCRIPT_SH >> $SUBMIT_SH

set -x
$SUBMITTER $SUBMIT_SH
