
:toc:

= unified-impeccable

These original shell scripts were on Frontier at:

`/lustre/orion/chm155/proj-shared/apbhati/IMPECCABLE_2.0/DEBUG_RUN`

== Steps

Step 1 "HTP Docking"::
Code is `/htp_docking`
+
`sub_p1_s1`: WALLTIME=20m
+
* Single big mpi4py run...
* Frontier: success in <22 minutes
* Aurora:   success in <?? minutes
** Needs `module frameworks` plus `rdkit`
** Uses environment `steps123`

Step 2: "Surrogate Training"::
Code is `/surrogate_training`
+
`sub_p1_s2`: - WALLTIME=1h
+
* MPI layout TOTALLY DIFFERENT?
* Frontier: success in <10 minutes
* Aurora:   works now: 2026-01-20
** Needs `module frameworks/2024` plus `horovod keras tensorflow IPython` and
   `pip SmilesPE` in
** Uses environment `steps123`

Step 3: "Surrogate Inference"::
Code is `/surrogate_inference`
+
* Frontier: `sub_p1_s3` - WALLTIME=1h - success in <10 minutes
* Aurora:   `sub_p1_s3` - WALLTIME=1h - success in <10 minutes
** Needs TensorFlow, mpi4py, Pandas

Step 4a: "Pose Generation"::
Code is `/pose_generation`
+
* Frontier: `sub_p2_s4a` - WALLTIME=1h - success in <2 minutes
* Aurora:   `sub_p2_s4a` - success in <5 minutes
** Needs `module frameworks/2024`
** `conda install mdanalysis`
** Can merge with environment steps123

Step 4b: "Amber"::
** Needs `module frameworks/2024`
** `conda install ambertools` (mmpbsa.py) (mmpbsa.py.MPI)
** Can merge with environment steps123

Step 4c: "NAMD"::
* Waiting for Wei

Step 4d: "MMPBSA"::
* Same ambertools environment, mmpbsa.py


Step 5: ::
* Same ambertools and NAMD environments

Step 6: "REINVENT"::
* conda ? reinvent

== Script architecture

=== Naming conventions

`CODE_DIR`::
The original location of the code in the IMPECCABLE-2.0 repo.

`WORK_DIR`::
The code is copied here for execution.

`MEM_DIR`::
A subdirectory of `WORK_DIR` for step data.  This is the `PWD` for the science code execution.  Short for "member directory".

`THIS`::
The directory containing the current script.  On Frontier/Slurm, this is found with a Slurm-specific variable.  On Aurora/PBS, we can use `PBS_O_WORKDIR`.  But it is better to look this up for each run script for interactive cases where the user may `cd` from the original submit-time directory.

`WORKFLOW_DIR`::
The top-level directory `unified-impeccable/workflow`

`WORKFLOW_STEP`::
The step-level directory `unified-impeccable/workflow/stepN`

=== Workflow-level scripts

* `site-SITE-settings.sh`
** General Software
*** Sets up non-Python software (licenses, schedulers)
** Python Settings
*** Loads Anaconda, etc.
** User Settings
*** Specific to the user that cloned the workflow.  User must specify the location of the IMPECCABLE clone and a desired output directory.
* `impeccable-settings.sh`
** Application-level settings for a specific science run.
** User may edit this to set `SMILES_INPUT`, `RECEP_FILE`, `INFERENCE_DATA` locations, etc.
* `job-settings.sh`
** System-level settings for each step.  Includes `WALLTIME`, `NODES`, `QUEUE`, etc.

== Typical user scenario

How to get started.

=== Set up

. Clone IMPECCABLE - Use Wozniak's fork:
+
----
git@github.com:j-woz/IMPECCABLE_2.0.git
----
+
. Clone this workflow repo
. Copy
.. `site-SITE-template.sh` to `site-SITE-settings.sh`
.. `impeccable-template.sh` to `impeccable-settings.sh`
.. Thus, `*-settings.sh` files are local and should not be pushed to git.
. Edit `setup-SITE.sh` for license and any other software, including Python
. Obtain inference data
.. On Frontier, at: +
`/lustre/orion/chm155/proj-shared/apbhati/InferenceData` +
.. On Aurora, at: +
`/lus/flare/projects/workflow_scaling/wozniak/IMPECCABLE/InferenceData`
You can point to this or make a copy.
. Copy `impeccable-template.sh` to `impeccable-settings.sh` and edit to set up the `INFERENCE_DATA` location, etc. for your use
. Start step with `impecc-job`
. The user should not need to install or configure any software.  See <<conda_envs,Anaconda environments>> below.
. Add directory `.../unified-impeccable/workflow` to `PATH` .  This contains the tool `impecc-job` .

=== Run a step

Steps must be run in order to produce all the intermediate data.

. `cd` into `stepN`
. Run either:
.. Interactive:
... Get an <<ui_session,interactive session>> running
... Run:
+
----
$ impecc-job bash sub_pP_sN-SITE.sh job-settings.sh
----
+
.. Scheduled on Aurora:
... Run:
+
----
$ impecc-job qsub sub_pP_sN-SITE.sh job-settings.sh
----

== Step progress model

. Each step has "step scripts" named `stepN/sub_pP_sN-SITE.sh`, for phase `P`, step `N`, and site `SITE`.
. User invokes `impecc-job` on the step script.  This submits the job to the scheduler or runs it interactively.  See <<impecc-job>> below.
. This runs `stepN/sub_pP_sN-SITE.sh` ,
.. which refers to `../site-SITE-settings.sh` for site settings and
.. loads application settings from `../impeccable-settings.sh`
. `sub_pP_sN-SITE.sh`:
.. sources `sub_pP_sN-setup.sh`, whicih:
... Sets up `CODE_DIR`, `WORK_DIR`, `MEM_DIR`
... Copies software to `WORK_DIR`
... Filters input files via `m4` (e.g., JSON)
.. contains the SITE-specific scheduler settings and
.. invokes the science codes via `mpiexec`, `srun`, etc.

== impecc-job

This lightweight shell script is our workflow tool.  Usage:

----
$ impecc-job LAUNCHER STEP_SCRIPT SETTINGS
----

where:

`LAUNCHER`::
`bash` for interactive, or `qsub` or `srun` to submit.

`STEP_SCRIPT`::
The step script itself.

`SETTINGS`::
The job settings script which contains node counts and other system configuration information for the scheduler and compute hardware.  Conventionally called `job-settings.sh`.  Examples of these for each step are in the GitHub repo.

`impecc-job` does these things:

. Injects settings into the step script via `m4`.  For ease of maintenance, we limit ourselves to the use of `m4_getenv(X)`, which injects environment variable `X` at that point in the file.
. Copies the edited step script into the `IMPECCABLE_WORK` directory, which is specified in the settings file.
. Runs the step script.

== Anaconda environments
[[conda_envs]]

We call this `CONDA_ENVIRONMENT`.

* step1: oepython_new
* step2: st_train
* step3: st_mpi_base

This is specified for each step by `sub_pP_sN-SITE.sh` , which passes it into the `sub_pP_sN-setup.sh` script, which passes it to `site-SITE-settings.sh`, which activates that environment after loading Python for that site.

=== Frontier

=== Aurora

On Aurora, the software is loaded by the `*-aurora.sh` scripts, which load necessary modules and activate Python environments.  We made clones of the main environments in `PY-IMPECCABLE.tar`, and added the additional science packages there.  These environments are automatically unpacked into `/tmp` at runtime for use by the workflow.

==== Python installations

The Python installations are noted for each step in the `*-aurora.sh` scripts.  When the `*-setup.sh` scripts are sourced, they are passed a `CONDA_INSTALLATION` and `CONDA_ENVIRONMENT`.

===== Example

In step3 we have:

----
source $WORKFLOW_STEP/sub_p1_s3-setup.sh \
       /opt/aurora/25.190.0/oneapi/intel-conda-miniforge \
       /tmp/PY-IMPECCABLE/step3
----

The workflow:
. Automatically unpacks `PY-IMPECCABLE.tar`
. Initializes the given `intel-conda-miniforge`
. Activates `PY-IMPECCABLE/step3`

==== Steps

The tarball `PY-IMPECCABLE.tar` contains multiple Anaconda environments, possibly one for each step.  It is created by cloning the ALCF Anaconda environments, then adding packages to them, then creating the tarball.  We use `workflow/install-py-pkgs.sh` to keep track of what packages we are adding.

Installs to `P=/tmp/PY-IMPECCABLE`
with subdirectories:

`$P/step1`::
`frameworks` plus `pydantic-settings openeye-toolkits rdkit`

`$P/step2`::
`tensorflow` plus `pandas`

`$P/step2`::
`frameworks` plus REINVENT

==== Python installation notes

To build/edit the conda environment for a step:

. Change the module settings in `*-aurora.sh`
. Edit the `PY-IMPECCABLE.tar` as indicated below

----
$ TAR=/lus/flare/projects/IMPECCAFLOW/wozniak/conda-tar/PY-IMPECCABLE.tar
# Unpack the tarball:
$ tar -xfz $TAR -C /tmp
# Possibly overwrite a step with a new clone:
$ E=$CONDA_PREFIX
$ P=/tmp/PY-IMPECCABLE
$ conda-clone
# Edit the packages in the environment
$ workflow/install-py-pkgs.sh
# Repack the tarball:
$ tar -c -C /tmp -f $TAR PY-IMPECCABLE
----

=== Inspecting environments

To see what we put in the environments for each step:

. See the `*-setup.sh` script for the step to see what installation and environment is used.
. See `workflow/install-py-pkgs.sh` to see what packages were installed into `PY-IMPECCABLE.tar` for each step.  `install-py-pkgs.sh` is currently a rough sketch, and cannot be run directly, but it does contain running notes for what packages and versions are used for `conda install` and `pip install` .

== Interactive sessions
[[ui_session]]

=== Aurora

Our project on Aurora is IMPECCAFLOW.

Use something like:

----
qsub -I -l select=1 -l walltime=60:00 -A IMPECCAFLOW -q debug -l filesystems=home:flare
----

== TODO

=== Justin



Insert DB commands

Create settings file with:
  PROJECT/ACCOUNT
  IMPECCABLE location - DONE

Per-campaign job directory
  EXP001, EXP002, ...

Output stream from job should go into job output directory

PSI/J

=== Ketan

Try step4

== Troubleshooting

MPI errors on Aurora::
Be sure to load the appropriate `frameworks` module that matches the Python you are using.

Step2 had sycl.8 error with frameworks/2024
